import numpy as np

import env


class Rule:
    RULE_NUM = 5

    def __init__(self, mission_env=None):
        self.mission_env = mission_env

    def to_env_action(self, rule_action, mission_env=None):
        if mission_env is None:
            mission_env = self.mission_env
        if mission_env is None:
            raise ValueError("mission_env must be provided.")

        rule_action = int(rule_action)
        if rule_action < 0 or rule_action >= self.RULE_NUM:
            raise ValueError(f"Unknown rule action: {rule_action}")

        candidates = self.operation_candidates(mission_env)
        if not candidates:
            raise ValueError("No valid assign action can be generated by rule action.")

        rule_keys = [
            lambda item: (item["system_wait_time"], item["start_time"], item["op_idx"], item["task_idx"],),
            lambda item: (item["start_time"], item["op_idx"], item["task_idx"],),
            lambda item: (item["duration"], item["start_time"], item["op_idx"], item["task_idx"],),
            lambda item: (item["start_time"],item["system_wait_time"],item["op_idx"],item["task_idx"], ),
            lambda item: (item["start_time"],item["duration"],item["op_idx"],item["task_idx"],),
        ]
        candidate = min(candidates, key=rule_keys[rule_action])
        sys_idx = self.cssa(
            mission_env,
            candidate["task_idx"],
            candidate["op_idx"],
            candidate["sys_indices"],
        )

        return int(
            mission_env.encode_action(
                "assign_task",
                task_idx=candidate["task_idx"],
                op_idx=candidate["op_idx"],
                sys_idx=sys_idx,
            )
        )

    def operation_candidates(self, mission_env):
        assign_mask = mission_env.mask_invalid_assign()
        valid_assigns = np.argwhere(assign_mask == 1)

        candidates = {}
        for task_idx, op_idx, sys_idx in valid_assigns:
            task_idx = int(task_idx)
            op_idx = int(op_idx)
            sys_idx = int(sys_idx)
            key = (task_idx, op_idx)
            op = mission_env.state.mission[task_idx].operations[op_idx]
            sys_available_time = float(mission_env.state.sys_availble_time[sys_idx])
            start_time = max(
                float(mission_env.state.current_time),
                sys_available_time,
                float(mission_env.state.op_release_time[task_idx, op_idx]),
            )
            system_ready_time = max(
                float(mission_env.state.current_time),
                sys_available_time,
            )
            system_wait_time = max(0.0, start_time - system_ready_time)

            if key not in candidates:
                candidates[key] = {
                    "task_idx": task_idx,
                    "op_idx": op_idx,
                    "sys_indices": [],
                    "start_time": start_time,
                    "duration": float(op.duration),
                    "system_wait_time": system_wait_time,
                }
            else:
                candidates[key]["start_time"] = min(
                    candidates[key]["start_time"],
                    start_time,
                )
                candidates[key]["system_wait_time"] = min(
                    candidates[key]["system_wait_time"],
                    system_wait_time,
                )

            candidates[key]["sys_indices"].append(sys_idx)

        return list(candidates.values())

    def cssa(self, mission_env, task_idx, op_idx, sys_indices):
        op = mission_env.state.mission[task_idx].operations[op_idx]

        candidates = []
        for sys_idx in sys_indices:
            start_time = max(
                float(mission_env.state.current_time),
                float(mission_env.state.sys_availble_time[sys_idx]),
                float(mission_env.state.op_release_time[task_idx, op_idx]),
            )
            finish_time = start_time + float(op.duration)
            if finish_time > float(env.FULL_SOS[sys_idx].available_until):
                continue

            candidates.append(
                (
                    start_time,
                    finish_time,
                    float(mission_env.state.sys_busy_time[sys_idx]),
                    int(sys_idx),
                )
            )

        if not candidates:
            raise ValueError(f"No feasible system for task {task_idx}, operation {op_idx}.")

        _, _, _, sys_idx = min(candidates)
        return sys_idx
