import numpy as np


class Rule:
    RULE_NAMES = ("SPT", "WINQ", "CR", "MS")
    RULE_NUM = len(RULE_NAMES)

    def __init__(self, mission_env):
        self.mission_env = mission_env

    def to_env_action(self, rule_action):
        rule_action = int(rule_action)
        if rule_action < 0 or rule_action >= self.RULE_NUM:
            raise ValueError(f"Unknown rule action: {rule_action}")

        candidates = self.operation_candidates()
        if not candidates:
            raise ValueError("No valid assign action can be generated by rule action.")

        def sort_key(candidate):
            if rule_action == 0:
                metric = candidate["duration"]
            elif rule_action == 1:
                metric = candidate["next_type_load"]
            elif rule_action == 2:
                metric = candidate["ttd"] / max(candidate["remaining_time"], 1.0)
            else:
                metric = candidate["slack"]
            return metric, candidate["start_time"], candidate["task_idx"], candidate["op_idx"]

        selected = min(candidates, key=sort_key)

        sys_idx = self.cssa(
            selected["task_idx"],
            selected["op_idx"],
            selected["sys_indices"],
        )
        return self.mission_env.encode_assignment(
            selected["task_idx"],
            selected["op_idx"],
            sys_idx,
        )

    def operation_candidates(self):
        mission_env = self.mission_env
        assignment_mask = mission_env.valid_assignment_mask()
        candidates = []

        for task_idx in range(mission_env.T):
            op_idx = int(mission_env.state.task_op_idx[task_idx])
            if op_idx == mission_env.O:
                continue
            sys_indices = np.flatnonzero(assignment_mask[task_idx, op_idx])
            if sys_indices.size == 0:
                continue

            operation = mission_env.mission[task_idx].operations[op_idx]
            candidates.append(
                {
                    "task_idx": task_idx,
                    "op_idx": op_idx,
                    "sys_indices": sys_indices,
                    "start_time": float(mission_env.state.task_earliest_start[task_idx]),
                    "duration": float(operation.duration),
                    "remaining_time": float(mission_env.state.task_remaining_time[task_idx]),
                    "ttd": float(mission_env.state.task_ttd[task_idx]),
                    "slack": float(mission_env.state.task_slack[task_idx]),
                    "next_type_load": float(mission_env.state.task_next_type_load[task_idx]),
                }
            )

        return candidates

    def cssa(self, task_idx, op_idx, sys_indices):
        mission_env = self.mission_env
        candidates = []

        for sys_idx in sys_indices:
            times = mission_env.assignment_times(task_idx, op_idx, sys_idx)
            if times is None:
                continue
            start_time, finish_time = times

            candidates.append(
                (
                    start_time,
                    finish_time,
                    float(mission_env.state.system_busy_time[sys_idx]),
                    int(sys_idx),
                )
            )

        if not candidates:
            raise ValueError(f"No feasible system for task {task_idx}, operation {op_idx}.")

        _, _, _, sys_idx = min(candidates)
        return sys_idx
