import numpy as np


class HRule:
    """Huang et al. (2023) operation-selection rules.

    The paper uses three single-rule metrics:

    - component-system waiting time
    - earliest executable time
    - operation execution time

    In the current offline tail-append environment, these map to the idle time
    introduced on the CSSA-selected system, cached assignment start time, and
    operation duration, respectively.
    """

    RULE_NAMES = (
        "H1_WAIT_EARLIEST",
        "H2_EARLIEST",
        "H3_SPT_EARLIEST",
        "H4_EARLIEST_WAIT",
        "H5_EARLIEST_SPT",
    )
    RULE_DESCRIPTIONS = (
        "minimum system waiting time, then earliest executable time",
        "earliest executable time",
        "shortest execution time, then earliest executable time",
        "earliest executable time, then minimum system waiting time",
        "earliest executable time, then shortest execution time",
    )
    RULE_NUM = len(RULE_NAMES)

    def __init__(self, mission_env):
        self.mission_env = mission_env

    def to_env_action(self, rule_action):
        rule_action = int(rule_action)
        if rule_action < 0 or rule_action >= self.RULE_NUM:
            raise ValueError(f"Unknown Huang rule action: {rule_action}")

        candidates = self.operation_candidates()
        if not candidates:
            raise ValueError("No valid assignment can be generated by Huang rules.")

        selected = min(
            candidates,
            key=lambda candidate: self.candidate_key(rule_action, candidate),
        )
        return self.mission_env.encode_assignment(
            selected["task_idx"],
            selected["op_idx"],
            selected["sys_idx"],
        )

    def candidate_key(self, rule_action, candidate):
        wait_time = candidate["wait_time"]
        start_time = candidate["start_time"]
        duration = candidate["duration"]
        task_idx = candidate["task_idx"]
        op_idx = candidate["op_idx"]

        if rule_action == 0:
            return wait_time, start_time, task_idx, op_idx
        if rule_action == 1:
            return start_time, task_idx, op_idx
        if rule_action == 2:
            return duration, start_time, task_idx, op_idx
        if rule_action == 3:
            return start_time, wait_time, task_idx, op_idx
        return start_time, duration, task_idx, op_idx

    def operation_candidates(self):
        mission_env = self.mission_env
        assignment_mask = mission_env.valid_assignment_mask()
        candidates = []

        for task_idx in range(mission_env.T):
            op_idx = int(mission_env.state.task_op_idx[task_idx])
            if op_idx >= mission_env.O:
                continue

            sys_indices = np.flatnonzero(assignment_mask[task_idx, op_idx])
            if sys_indices.size == 0:
                continue

            sys_idx = self.cssa(task_idx, op_idx, sys_indices)
            start_time = float(
                mission_env.assignment_start_time[task_idx, op_idx, sys_idx]
            )
            system_ready_time = float(
                mission_env.state.system_ready_time[sys_idx]
            )
            operation = mission_env.mission[task_idx].operations[op_idx]
            candidates.append(
                {
                    "task_idx": task_idx,
                    "op_idx": op_idx,
                    "sys_idx": sys_idx,
                    "wait_time": max(start_time - system_ready_time, 0.0),
                    "start_time": start_time,
                    "duration": float(operation.duration),
                }
            )

        return candidates

    def cssa(self, task_idx, op_idx, sys_indices):
        mission_env = self.mission_env
        candidates = []

        for sys_idx in sys_indices:
            start_time = float(
                mission_env.assignment_start_time[task_idx, op_idx, sys_idx]
            )
            finish_time = float(
                mission_env.assignment_finish_time[task_idx, op_idx, sys_idx]
            )
            candidates.append(
                (
                    start_time,
                    finish_time,
                    float(mission_env.state.system_busy_time[sys_idx]),
                    int(sys_idx),
                )
            )

        if not candidates:
            raise ValueError(
                f"No feasible system for task {task_idx}, operation {op_idx}."
            )

        return min(candidates)[3]
